version: "3"
services:
  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    environment:
      - address=61184328cfd30d8caa78438884d5322ce203c045 #derived from the private key which is passed in the args
      - bootnodeId=enr:-KO4QF1_8nz3bsVqqlzY6KZZ9junO2yXJtVP13UoVGJYKH-zX96T8KRBeONADS0Zwr52InchNzMZT6-L7eNONauCxIKGAYXKeuweg2V0aMfGhHFdi6mAgmlkgnY0gmlwhLKAdKqJc2VjcDI1NmsxoQMP5N_1MYJHmhcCiJvproEvxABgt01zPoapktpGiQ5onYRzbmFwwIN0Y3CCf5yDdWRwgn-c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=178.128.116.170
    build:
      context: .
      dockerfile: ./minerdeploy/Dockerfile
      args:
        privatekey: f8fe1beff5109af3fd61fa753e806484fd6e6f8617b251dcad7b4b9a724f26f5 # Please don't do something like this in production, okay?
        password: 123456
    ports:
      - 8546:8545
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address
    healthcheck:
      test: wget http://localhost:8546
      interval: 2s
      timeout: 5s
      retries: 30
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
